### PR TITLE
Space between type name and "unsigned"

### PR DESCRIPTION
**Pull request by subdir**
Seems like it may be missing unintentionally.

### CODE REVIEW

**Comment by lukaseder** [comment]
Thanks for the hint and suggestion.

This does look weird, although, it might be a workaround for a problem from the very early days of jOOQ. I'm going to be careful with merging this pull request... Did you run into an actual issue?

**Comment by subdir** [comment]
> Did you run into an actual issue?

No, it just makes me think like I should write
```java
ForcedType.withName("bigint").withTypes("intunsigned");
```
instead of
```java
ForcedType.withName("bigint").withTypes("int unsigned");
```

And whatever I choose, it feels a little fragile.

**Comment by lukaseder** [comment]
Thanks for the additional feedback. Yes, it is fragile. So are data type names as provided by the individual database vendors.

jOOQ follows a very lenient policy when it comes to matching data types. E.g. whitespace is ignored in order to make things like `number(1)` and `number ( 1 )` the same thing. But I'm sure there's potential for improving these things.

If you want to stay on the safe side, put a regular expression there, which matches different renderings of your type...

**Comment by subdir** [comment]
Thanks for you answer.

> If you want to stay on the safe side, put a regular expression there, which matches different renderings of your type...

In some situations excessive regular expressions could be as dangerous as fixed type strings.

Not sure about other DBEs but the way you parse data types for MySQL is pretty strong and parsing results are deterministic so I would like to count on it. But may be it's a bad idea to count on implemetation details.

**Comment by lukaseder** [comment]
> Not sure about other DBEs but the way you parse data types for MySQL is pretty strong and parsing results are deterministic so I would like to count on it.

Well, I wish the MySQL dictionary views were more reliable. They're not so easy to work with at times...

> But may be it's a bad idea to count on implemetation details.

Yes... It depends :)

**Comment by lukaseder** [comment]
I'm rejecting this for now. Since there isn't any concrete issue, I'm afraid that accepting the suggested change might introduce a regression.

**Pull request closed without merging**
