### PR TITLE
[#8090] - xmldatabase array support

### PR DESCRIPTION
**Pull request by PatrickJSweeney**
to be utilized from XMLGenerator and XMLTableDefinition

https://github.com/jOOQ/jOOQ/issues/8090

### CODE REVIEW

**Comment by PatrickJSweeney** [comment]
@lukaseder I need this fix under jdk8 for my personal needs.  It cherry-picked cleanly back to v3.11.7.  Please let me know if there is anything else I can do.

**Comment by PatrickJSweeney** [comment]
K.  I promise I'm done with the force-pushes now.  I was just trying to match the https://github.com/jOOQ/jOOQ/blob/master/CONTRIBUTING.md

**Comment by lukaseder** [comment]
Thank you for offering your help with this task, @PatrickJSweeney. Unfortunately, I must reject this PR.

The SQL standard `INFORMATION_SCHEMA` specifies a variety of columns in the `INFORMATION_SCHEMA.COLUMNS` view, including `(UDT_CATALOG, UDT_SCHEMA, UDT_NAME)`, which are derived from the `DEFINITION_SCHEMA.DATA_TYPE_DESCRIPTOR` table. If we do decide to add support for arrays, it is crucial to specify their contents in a new standards compliant `INFORMATION_SCHEMA.ELEMENT_TYPES` table.

**Comment by PatrickJSweeney** [comment]
@lukaseder  I don't think I understood your original comments in #8090, thus my incomplete implementation.  I thought referencing the bare minimum udt columns from information_schema would be least invasive.

Could you supply a link to the spec you are referencing?  My google searches do not yield any results that line up with your description.  I may want to propose a number of improvements to XMLDatabase and would like to avoid any future miscommunication about your guidance on the implementation.

**Comment by PatrickJSweeney** [comment]
@lukaseder After some digging, I see that the SQL standard is not free (or cheap for an individual hobbyist). Disregard my previous request.  If I do more work in this area, I'll reference your implementation for this bug as the pattern to follow and hope for the best.

**Comment by lukaseder** [comment]
@PatrickJSweeney I'm sorry for the confusion. The point I'm trying to mainly hint at here is that changing things in jOOQ is not as simple as it may look at first. While I do appreciate the intent, usually I prefer doing a change myself rather than discussing the various requirements of a possible PR, which is both more time consuming for everyone and far from a guarantee to a better result.

In addition to this, from a project and product management perspective, one would not expect that a feature can be implemented so quickly without deeper knowledge of the product internals and/or roadmap, and this doesn't touch the topic of prioritisation. Here, we have two edge case features: arrays and the `XMLDatabase`. Fixing this quickly will deteriorate the quality of the product in an already edge casey area. Fixing this thoroughly will be very time consuming and definitely not something that could be expected from an external contributor.

I just wish github would allow for turning on the issue tracker feature without also necessarily turning on the pull request feature. The workflow should always be: Discuss first, and then probably, not implement later :-)

**Pull request closed without merging**
