### PR TITLE
Fixes #9670 to make jooq OSGi backwards compatible for slf4j and also…

### LINKED ISSUE #9670: Make slf4j-api version backwards compatible
jooq 3.12.3 release is using slf4j-api v1.8 (beta4). As many of us are using stable releases such as the slf4j 1.7 api, then this fails, especially on OSGi where you get this kind of error

I wonder if can make the OSGi version range be [1.7,2)" or maybe go back to using a stable 1.7 version. You marked it as optional and provided by it can hardly be optional if you have java imports on this API in jooq.

> RROR] Message: Unable to resolve root: missing requirement [root] osgi.identity; osgi.identity=camel-jooq; type=karaf.feature; version=3.1.0.SNAPSHOT; filter:="(&(osgi.identity=camel-jooq)(type=karaf.feature)(version>=3.1.0.SNAPSHOT))" [caused by: Unable to resolve camel-jooq/3.1.0.SNAPSHOT: missing requirement [camel-jooq/3.1.0.SNAPSHOT] osgi.identity; osgi.identity=org.apache.camel.camel-jooq; type=osgi.bundle; version="[3.1.0.SNAPSHOT,3.1.0.SNAPSHOT]"; resolution:=mandatory [caused by: Unable to resolve org.apache.camel.camel-jooq/3.1.0.SNAPSHOT: missing requirement [org.apache.camel.camel-jooq/3.1.0.SNAPSHOT] osgi.wiring.package; filter:="(&(osgi.wiring.package=org.jooq.impl)(version>=3.12.0)(!(version>=4.0.0)))" [caused by: Unable to resolve jooq/3.12.3: missing requirement [jooq/3.12.3] osgi.wiring.package; filter:="(&(osgi.wiring.package=org.slf4j)(version>=1.8.0)(!(version>=2.0.0)))"]]]

### PR DESCRIPTION
**Pull request by davsclaus**
… fix the bundle to not import itself.

Signed-off-by: Claus Ibsen <claus.ibsen@gmail.com>

### CODE REVIEW

**Comment by davsclaus** [comment]
Now it works, and can be installed in OSGi container such as Apache Karaf

These are the osgi headers being imported now

```
Import-Package =
	javax.persistence;resolution:=optional;version="[2.2,3)",
	org.slf4j;resolution:=optional;version="[1.7,2)",
	javax.annotation.processing,
	javax.sql,
	javax.tools,
	javax.xml.bind;version="[2.3,3)",
	javax.xml.bind.annotation;version="[2.3,3)",
	javax.xml.bind.annotation.adapters;version="[2.3,3)",
	javax.xml.namespace,
	javax.xml.parsers,
	javax.xml.transform,
	javax.xml.transform.dom,
	javax.xml.transform.stream,
	javax.xml.validation,
	org.reactivestreams;version="[1.0,2)",
	org.w3c.dom,
	org.xml.sax,
	org.xml.sax.helpers
```

**Comment by davsclaus** [comment]
And these are the older working version
```
Import-Package =
	javax.persistence;resolution:=optional;version="[2.2,3)",
	org.apache.log4j;resolution:=optional;version="[1.2,2)",
	javax.sql,
	javax.tools,
	javax.xml.bind;version="[2.2,3)",
	javax.xml.bind.annotation;version="[2.2,3)",
	javax.xml.bind.annotation.adapters;version="[2.2,3)",
	javax.xml.namespace,
	javax.xml.parsers,
	javax.xml.transform,
	javax.xml.transform.dom,
	javax.xml.transform.stream,
	org.jooq,
	org.jooq.conf,
	org.jooq.exception,
	org.jooq.impl,
	org.jooq.tools,
	org.jooq.tools.csv,
	org.jooq.tools.jdbc,
	org.jooq.tools.json,
	org.jooq.tools.reflect,
	org.jooq.types,
	org.jooq.util.cubrid,
	org.jooq.util.derby,
	org.jooq.util.firebird,
	org.jooq.util.h2,
	org.jooq.util.hsqldb,
	org.jooq.util.jaxb.tools,
	org.jooq.util.mariadb,
	org.jooq.util.mysql,
	org.jooq.util.postgres,
	org.jooq.util.sqlite,
	org.jooq.util.xml.jaxb,
	org.slf4j;resolution:=optional;version="[1.7,2)",
	org.w3c.dom,
	org.xml.sax,
	org.xml.sax.helpers
```

**Comment by lukaseder** [comment]
Thanks again for your contribution. I'll merge this now.

We currently don't have any integration tests for this. Do you have any ideas for what common pitfalls would be worth testing on our side? I'd like to add some tests in this area, but without OSGi experience, I'm not sure what to test...

**Comment by davsclaus** [comment]
> Thanks again for your contribution. I'll merge this now.
> 
> We currently don't have any integration tests for this. Do you have any ideas for what common pitfalls would be worth testing on our side? I'd like to add some tests in this area, but without OSGi experience, I'm not sure what to test...

Oh testing in OSGi is frankly tough. At basic test is to be able to just deploy jOOQ in an OSGi container. 

Then you would essentially need a suite of tests as you would normally run for unit tests, as OSGi can have its "surprises". Especially with class-loading, and when using 3rd party JARs where their maven dependency tree vs OSGi MANIFEST are not aligned, so when something works outside OSGi, then its OSGi import|export (and other bits) could be wrong, and cause something to not work there, and you may only know this when you use these parts of the code etc.

For some basic OSGi testing, you can use pax-exam and use Apache Karaf as the OSGi container. We have a tiny camel-osgi-activator component that tests itself a bit standalone like this
https://github.com/apache/camel/tree/master/components/camel-osgi-activator

For a more basic osgi container you can use Apache Felix or Eclipse Equinox

**Comment by lukaseder** [comment]
OK, thanks, @davsclaus

**Pull request merged**
