### PR TITLE
[#6604] Improve INSERT .. VALUES API for dynamic multi-row inserts

### PR DESCRIPTION
**Pull request by Diagoras**
https://github.com/jOOQ/jOOQ/issues/6604

### CODE REVIEW

**Comment by lukaseder** [comment]
Thank you for your suggestion. We're far from reaching consensus on what should be done here syntactically or semantically, nor whether anything should be done at all. I can thus not accept this PR.

**Comment by Diagoras** [comment]
@lukaseder Got it. What would you need to see in order to accept PRs for this issue? A more definitive conversation and conclusion in the related issue? Something else?

Also, is there something I should be looking for to determine whether an issue is good to work on? Like a "contributions-wanted" label or something on issues that are considered open to contributions? Just want to avoid doing this again.

**Comment by lukaseder** [comment]
> What would you need to see in order to accept PRs for this issue? A more definitive conversation and conclusion in the related issue? Something else?

There's a big problem on Github. It does not allow to activate the issue tracker without activating the PR subsystem. In fact, apart from typos and obvious bug fixes, I prefer not to get any PRs at all. jOOQ has become quite complex and adding a feature is a very costly endeavour (not as complex as adding something to the Java language, yet, but we're getting there).

The idea that PRs are a thing implies that users can re-prioritise efforts around an individual feature, which I don't think is such a high priority. Also, believe it or not, I don't believe in "community driven" open source. The efforts for the maintainer to review, improve, merge contributions are in now reasonable relation to the benefit of not "having to do the work". After all, the actual implementation is usually the least amount of work. Designing a feature is the big part. And as you're already suggesting, this will need a *"more definitive conversation"*, which I currently don't want to have (because of priorities).

> Also, is there something I should be looking for to determine whether an issue is good to work on? Like a "contributions-wanted" label or something on issues that are considered open to contributions? Just want to avoid doing this again.

Yes. Please don't :) I'm sorry to disappoint you here, but think of jOOQ like the Oracle Database. You usually wouldn't want to provide code, let alone features to it (the exception being "obvious" bug fixes). But you like using it, so the best thing to contribute is feedback, bug reports, etc.

A long time ago, there was a contributions-wanted label. I've removed it because it caused more trouble than benefit with tons "contributors" who needed tons of training to get going only to contribute 1-2 minor features. It simply doesn't scale.

**Comment by Diagoras** [comment]
@lukaseder Ah, got it. That clears a lot of things up, thanks.

> By the way. This feels like RTFM'ing... Sorry about that. We have this document here: https://github.com/jOOQ/jOOQ/blob/master/CONTRIBUTING.md

Yeah, I took that paragraph to mean "don't open a PR without opening an issue and talking about it first", not "don't open a PR for issues beyond bug fixes".

How would you feel about modifying the "CONTRIBUTING.md" to make what you've stated in this PR explicit to other wannabe contributors? Specifically, that jOOQ isn't interested in people opening PRs for anything beyond minor and obvious bug fixes, and that people should especially never open PRs for new features.

That was non-obvious to me, because of how different it is from the usual GitHub culture of open contribution for triaged issues. I understand and respect your reasons for not adopting that model, but I think that given it's the norm you might be better off if you make your policy clear. At the very least, you'd get fewer randos like me opening PRs against issues you haven't prioritized.

BTW, I'd be willing to open an example PR for that change. I'm guessing that you'll probably want to handle it yourself, though. ;)

**Comment by lukaseder** [comment]
> Yeah, I took that paragraph to mean "don't open a PR without opening an issue and talking about it first", not "don't open a PR for issues beyond bug fixes".

Well, we didn't "talk" about it yet, in the sense of having agreed to 1) what the API should look like, 2) whether this should be done at all :)

> How would you feel about modifying the "CONTRIBUTING.md" to make what you've stated in this PR explicit to other wannabe contributors? Specifically, that jOOQ isn't interested in people opening PRs for anything beyond minor and obvious bug fixes, and that people should especially never open PRs for new features.

I don't say never, but again, would you just go fork the Open JDK, implement tons of new Collection methods, provide a PR, and expect that PR to be merged?

Trivial PRs can be merged easily, because there's nothing to discuss. This here is quite big. You may not see it (yet), but adding new API like this needs to be added in a consistent way. This includes:

- Thinking about all the remaining API that deals with sets of records that needs to be considered
- Thinking about possible existing functionality, that should be merged with this one
- Thinking about the many places in the manual that need to be updated

This is just something that most aspiring contributors underestimate.

> That was non-obvious to me, because of how different it is from the usual GitHub culture of open contribution for triaged issues.

Well, jOOQ works well along the lines of this "culture". There are no such issues. You can browse them and contribute, except that you won't find any ;-)

> I understand and respect your reasons for not adopting that model, but I think that given it's the norm 

Who says this is the norm? There is bad UX on github's behalf, and there are hobbyist's projects, where quality doesn't matter. But I don't think you'll be able to add features that easily in more serious projects, without first discussing and *agreeing* with the maintainers about what should be done.

> you might be better off if you make your policy clear. At the very least, you'd get fewer randos like me opening PRs against issues you haven't prioritized.

I guess I will adapt the wording, indeed.

**Comment by Diagoras** [comment]
Sounds good. Let me know if I should open an issue for changing the wording of the "CONTRIBUTING.md", but for now I'll assume that's overkill unless told otherwise. Thanks for the feedback, and for maintaining this awesome database tool.

**Comment by lukaseder** [comment]
Hah, how meta :) I've updated the wording here: https://github.com/jOOQ/jOOQ/blob/master/CONTRIBUTING.md

I hope this makes it (would have made it) more clear. Thanks again for your understanding

**Comment by Diagoras** [comment]
@lukaseder That's perfect! I think that's absolutely clear about what jOOQ is looking for in PRs. Thanks.

**Pull request closed without merging**
