### PR TITLE
[#5873] Add Setting.quoteEscaping to allow for alternative escaping of single quote

### PR DESCRIPTION
**Pull request by zhurs**
https://github.com/jOOQ/jOOQ/issues/5873

### CODE REVIEW

**Comment by lukaseder** [comment]
Thank you very much for your suggested implementation. While I review, may I ask you to please read our contribution guidelines and sign the transfer of rights agreement linked in it?
https://github.com/jOOQ/jOOQ/blob/master/CONTRIBUTING.md

**Comment by lukaseder** [comment]
I've reviewed your suggestion. Very nice - seems complete, at first sight. Will check again with the integration tests after the agreement has been signed and the changes merged.

**Comment by zhurs** [comment]
Thank you for the super-fast response!
I read documents and electronically signed the transfer of rights agreement.

**Comment by lukaseder** [comment]
Thank you very much. Will merge on Monday

**Comment by lukaseder** [comment]
I'll rename the flag to ApostropheEscaping. The term "quote" or "quoting" in jOOQ referes to quoting identifiers, such as:

- `"abc"` (standard SQL)
- `[abc]` (T-SQL)
- `` `abc` `` (MySQL)

**Comment by lukaseder** [comment]
After giving this more thought, I'll revert your suggested implementation, it is incorrect. The original issue #5873 might have been a bit misleading because it suggested adding a new flag, when it shouldn't have (although there was a disclaimer: *we'll need to study the interaction between these two*).

The existing flag `Settings.backslashEscaping` currently governs MySQL-specific behaviour where both escaping through doubling the apostrophe *and* through using a backslash are possible. (This is of course nuts)

Now, the use-case described in #5873 is that *only* backslash escaping is possible in some dialects, e.g. SOQL. It is better to enhance the existing `BackslashEscaping` with an additional option:

- `OFF`: Backslash escaping is not possible (existing)
- `ON`: Backslash escaping is enabled, along with repeating apostrophe escaping (existing)
- `DEFAULT`: `ON` for MySQL and MariaDB, `OFF` for all the others
- `ONLY`: Backslash escaping is enabled, repeating apostrophe escaping is not enabled

The error in the suggested implementation lies in the fact that:

- The two flags are both conflicting and confusing
- When allowing to escape things using a backslash, then the backslash must escape *all* things, not just apostrophes. Very unfortunately, SOQL also proceeds to using the backslash for all sorts of other things: https://developer.salesforce.com/docs/atlas.en-us.soql_sosl.meta/soql_sosl/sforce_api_calls_soql_select_quotedstringescapes.htm

Since jOOQ doesn't actually support SOQL nor does jOOQ plan on doing so, I think I'll simply reject #5873. I'm sorry for the inconvenience this has caused.

**Pull request merged**
