### PR TITLE
[#6736] Add support for PostgreSQL ON CONFLICT conflict_target WHERE  ..

### PR DESCRIPTION
**Pull request by timur-sh**

### CODE REVIEW

**Comment by timur-sh** [comment]
To semantic reason I've used a `Keyword` type to distinguish an operator class. I don't have a pleasure on it. It should be changed in the future  on more suitable type.

**Comment by lukaseder** [comment]
Thanks for your suggestion. I will reject this PR in its entirety for the following reasons:

- The DSL API makes use of terminology that does not appear in SQL syntax, including:
  o `addOnConflict`. There's no `ADD` keyword
  o `whereIndex`. There's no `INDEX` keyword
- You hijacked feature request #6736 in order to add tons of additional features which we hadn't discussed first (some of which I prefer not to support):
  o The collation. We currently do not support collations or `collate` clauses, see #2908. There are many other places where collation support would be much more useful rather than in this arcane PostgreSQL-specific statement. Even if we did add support for the `collate` clause, it would have to be added using a `collate()` method, and a new `org.jooq.Collation` type (which we don't have right now)
  o The opclass. I really don't see the point of supporting this at this stage. Your (ab)using the `Keyword` type for this in the public API should be an indication that this addition was premature.
- The new public interface `OnConflictProvider` shouldn't be part of the public API. I doubt it should even be there at all.

If you want to try again, please restrict this particular change to add only the requested `WHERE` clause.

**Comment by timur-sh** [comment]
Thank you for your explanation. I'd like to complete this feature. To do it there are a several milestones:

Some points need to be changed:
-  `InserImpl#onConflict` can take a 'OnConflict` type

Some points need to be deleted
- The `InsertOnConflictStep` interface 
- The `collation` implementations
- The `opclass` implementations
- All `addOnConflict` methods
- The `OnConflictProvider` interface

But, I'm not sure what to do with `whereIndex` and `addIndexConditions`, because, `InsertIml` implements `where` methods.

Could you give any advices also?

**Comment by lukaseder** [comment]
> InserImpl#onConflict can take a 'OnConflict` type

I don't think that's the appropriate approach. Let's look at the grammar:

```
[ ON CONFLICT [ conflict_target ] conflict_action ]
where conflict_target can be one of:

    ( { index_column_name | ( index_expression ) } [ COLLATE collation ] [ opclass ] [, ...] ) [ WHERE index_predicate ]
    ON CONSTRAINT constraint_name
```

Now, the jOOQ way of translating this sort of grammar is to offer the following "overloads":

```
// index_column_name version
onConflict(Field<?>...)
onConflict(Collection<? extends Field<?>>)

// ON CONSTRAINT version
onConflictOnConstraint(Constraint)
```

> But, I'm not sure what to do with whereIndex and addIndexConditions, because, InsertIml implements where methods.

The fact that there is already a `where()` method in the implementation shouldn't leak into the API. There are similar cases in other implementations, where a `where()` method has several meanings. Have a look at `MergeImpl.where()`.

Since the current implementations of the DSL are mutable, we can easily "remember" what the last clause was, and then act accordingly. If the DSL were immutable, it would be even easier to implement.

Hope this helps

**Comment by timur-sh** [comment]
> // index_column_name version
onConflict(Field<?>...)
onConflict(Collection<? extends Field<?>>)

As you know, this works as `index_expression` version also.

**Comment by lukaseder** [comment]
> As you know, this works as index_expression version also.

Yes, that's probably not fully supported yet.

> When will be implemented collation and opclass clauses, it is be appropriate to use a type like OnConflict to group them.

No, why?

```java
create.insertInto(table, ...)
      ...
      .onConflict(fields)
      .collate(collation)
      .varcharPatternOps()
      ...
```

`COLLATE` is a keyword, so this translates to a method. The collation is an object reference, so this translates to a parameter. `opclass` is a placeholder for a set of possible keywords, which we can either hard-code in the API if the set is relatively small, or we add a synthetic keyword `OPCLASS`, which translates to a method `opclass(opclass)`.

There is really no need to create any wrapper around a set of parameters in the jOOQ DSL. Any such wrapper will be an impediment to learning the DSL API, which should map to the backing SQL syntax in the closest possible way as illustrated in this article that I've linked earlier:
https://blog.jooq.org/2012/01/05/the-java-fluent-api-designer-crash-course

Let's keep it simple (for the user) :-)

Hope this helps.

(And really, I'd love to see the use-case and at least 10 people asking for the feature before we'll add support for this arcane opclass thingy. We don't have to add support for every wacko vendor-specific feature (I really really wish PostgreSQL had supported SQL standard MERGE, rather than this weird `ON CONFLICT` nonsense))

**Pull request closed without merging**
