### PR TITLE
Fix routine parameter code generation for types with a binding

### PR DESCRIPTION
**Pull request by lightoze**

### CODE REVIEW

**Comment by lukaseder** [comment]
Thank you for your suggested change. In order to be able to dual-license your contribution to both the jOOQ Open Source Edition and the commercial distributions, we would need you to sign the following transfer of rights agreement:
http://www.jooq.org/legal/contributions

Please, let me know if this is OK with you, and if you have any specific questions regarding dual-licensing.

**Comment by lightoze** [comment]
I've accepted the agreement. Where is the mentioned “Help” or “About” file located? :)

**Comment by lukaseder** [comment]
Thank you very much. I'll review the change ASAP and let you know about my findings.

> Where is the mentioned “Help” or “About” file located? :)

Excellent question. There is a contributor listing in the parent pom.xml, and we usually add/maintain `@author` tags in the relevant classes, but we should definitely also maintain a complete "about" file. I've created an issue to fix this: #4431. Thanks for pointing this out to us!

**Comment by lightoze** [comment]
OK, hope to see it merged soon - the bug leads to uncompilable generated code for me.

**Comment by lukaseder** [comment]
Interesting, how can the compilation error be reproduced? E.g. what DDL and code generator configuration lead to it?

**Comment by lightoze** [comment]
I have a function with JSONB parameter which has a custom binding. Generated code is
```
Parameter<JsonElement> OBJ = createParameter("obj", org.jooq.impl.DefaultDataType.getDefaultDataType("jsonb"), false);
```
So `Parameter<Object>` cannot be assigned to `Parameter<JsonElement>`.

**Comment by lukaseder** [comment]
Ok, thanks for the additional info

**Pull request merged**
