### PR TITLE
[#7014] Add API to bind named parameters to plain SQL QueryParts

### PR DESCRIPTION
**Pull request by MMeent**
This MR implements #7014:

It adds a setting to opt-in to the new behaviour, and implements named parameter binding

The added behaviour of binding parameters is:
1.) gather all named parameters into a `Map<param_name, List<NamedParam<name=param_name>>` to deal with possibly duplicated names being bound
2.) for each named parameter that is found that is the Nth of that name, it binds the Nth entry in the list of that parameter name, or if that is out of bounds, the last entry of that parameter name.

### CODE REVIEW

**Comment by lukaseder** [comment]
Thanks for the suggestion. We'll consider it once this is prioritised.

**Comment by MuizMahdi** [comment]
Uninformative comment, but final issue for 3.15.0 🎉

**Comment by lukaseder** [comment]
Sorry @MuizMahdi, the 3.15 ship has sailed 😁

**Comment by lukaseder** [comment]
I'm closing this PR. While https://github.com/jOOQ/jOOQ/issues/7014 will be implemented eventually, the suggested implementation is probably not going to be the one that will make it.

**Pull request closed without merging**
