### PR TITLE
[#6812] Added GRANT statement and its implementation.

### PR DESCRIPTION
**Pull request by timur-sh**

### CODE REVIEW

**Comment by lukaseder** [comment]
Thank you very much for your contribution. That looks workable, thus far. I will fix a few minor things that are easier to just fix rather than discuss. Will commit soon and comment on the fixes thereafter.

**Comment by timur-sh** [comment]
Thank you!

**Comment by lukaseder** [comment]
Here are some changes that I've done:

- `DSL.privilege(Keyword)` is package-private for now. I'm not 100% convinced that privilege : keyword is a 1:1 relationship. There are probably more complex privileges, which cannot be modelled by a keyword alone. However, privileges can always be expressed by strings
- Moved methods around in `DSLContext`
- Added overload `DSLContext.grant(Privilege...)` for API consistency reasons. The same with `revoke()`. I'm leaving `grant(Privilege)` (and `revoke()`) as I'm assuming there are dialects that allow for only granting/revoking a single privilege at a time.
- Changed `DSL.grant()` and `DSL.revoke()` signatures to be exactly the same as those in `DSLContext`
- Added `execute()` calls to Javadoc (people were often confused when that call was lacking, in the past)
- Changed interface names, e.g. `GrantOnStep` (`Step` is always the suffix)
- Removed unused interfaces `GrantFirstStep` and `RevokeFirstStep`
- Added `GrantFinalStep` and `RevokeFinalStep` types, which are there for historic reasons and for edge cases in backwards compatible API evolution
- RevokeFromStep shouldn't extend Query, otherwise the from() clause would be optional. Same with Grant
- RevokeOnStep shouldn't extend RevokeFromStep, otherwise the on() clause would be optional. Same with Grant
- Added a third overload for on(Table) methods: on(Name)
- Annotated plain SQL API with @PlainSQL and the relevant Javadoc disclaimer
- Added the @Support annotation throughout the DSL
- Made all impl methods final
- Fixed clauses

**TODOs**

- I'm still not happy with the fact that we currently have a String as the privilege. There should be something better for the basic privileges
- I've run a quick integration test on Oracle, which works (see code below). Will do more testing next week.

```java
    public void testGrantRevoke() throws Exception {
        Table<?> t = table(name(schema().getName(), "t"));
        Field<Integer> i = field(name("i"), SQLDataType.INTEGER);
        DSLContext norights = using(getConnectionNoRights());
        User user = user(getConnectionNoRights().getMetaData().getUserName());

        try {
            create().createTable(t).columns(i).execute();
            assertEquals(0, create().fetchCount(t));
            assertThrows(DataAccessException.class, () -> norights.fetchCount(t));

            create().grant(privilege("select")).on(t).to(user).execute();
            assertEquals(0, norights.fetchCount(t));

            create().revoke(privilege("select")).on(t).from(user).execute();
            assertThrows(DataAccessException.class, () -> norights.fetchCount(t));
        }
        finally {
            ignoreThrows(create().dropTable(t)::execute);
        }
    }
```

**Comment by lukaseder** [comment]
Anyway, this works nicely so far. Well done! Further discussion / improvements will be made on the main ticket #6812

**Comment by timur-sh** [comment]
I've reviewed your aforementioned enhancements. It makes the API more readable and better. Thank you. About the `Privilege` we should improve it, such as we see  #6812, there are a lot of variate privileges

**Pull request merged**
