### PR TITLE
[5619] Add Field.containsIgnoreCase() to support Postgres' ILIKE operator

### PR DESCRIPTION
**Pull request by lmarchau**
Suggestion for issue #5619

### CODE REVIEW

**Comment by lukaseder** [comment]
Thank you very much for your contributions. I will look into both of them shortly.

As jOOQ is dual-licensed software, I need to kindly ask you to review our contribution guidelines and in particular our transfer of rights agreement linked from the guidelines:
https://github.com/jOOQ/jOOQ/blob/master/CONTRIBUTING.md

If you agree, please sign the agreement, and we can proceed with merging the PRs

**Comment by lukaseder** [comment]
Thank you very much. Will now review your suggestion, shortly

**Comment by lukaseder** [comment]
Thanks again. Will merge and fix issues directly on this PR in subsequent commits

**Comment by lmarchau** [comment]
You're welcome.

**Pull request merged**
