### PR TITLE
Close the Maven Plugin's URLClassLoader after code generation

### PR DESCRIPTION
**Pull request by SerCeMan**
Hi, @lukaseder! 

Thank you for jOOQ, it's great! Recently, I upgraded a large maven build to JDK10 (from JDK8), and the jOOQ build step started failing with "too many open files". It seems to be related to the fact that `java.util.zip.ZipFile#finalize` used to close the files on [JDK <= 9](http://hg.openjdk.java.net/jdk8/jdk8/jdk/file/tip/src/share/classes/java/util/zip/ZipFile.java#l662), but it was deprecated for removal and in [JDK10](http://hg.openjdk.java.net/jdk/jdk/file/tip/src/java.base/share/classes/java/util/zip/ZipFile.java#l910), and now it has an empty body. 

I ran `lsof` to see the list of open files.
```
count | filename
...
7 /var/lib/buildkite-agent/.m2/repository/org/w3c/css/sac/1.3/sac-1.3.jar
7 /var/lib/buildkite-agent/.m2/repository/software/amazon/ion/ion-java/1.0.2/ion-java-1.0.2.jar
8 /var/lib/buildkite-agent/.m2/repository/ch/qos/logback/logback-classic/1.2.3/logback-classic-1.2.3.jar
8 /var/lib/buildkite-agent/.m2/repository/ch/qos/logback/logback-core/1.2.3/logback-core-1.2.3.jar
8 /var/lib/buildkite-agent/.m2/repository/com/google/code/findbugs/jsr305/3.0.2/jsr305-3.0.2.jar
8 /var/lib/buildkite-agent/.m2/repository/com/google/guava/guava/20.0/guava-20.0.jar
8 /var/lib/buildkite-agent/.m2/repository/commons-io/commons-io/2.5/commons-io-2.5.jar
8 /var/lib/buildkite-agent/.m2/repository/io/sentry/sentry/1.7.2/sentry-1.7.2.jar
8 /var/lib/buildkite-agent/.m2/repository/io/sentry/sentry-logback/1.7.2/sentry-logback-1.7.2.jar
8 /var/lib/buildkite-agent/.m2/repository/javax/xml/bind/jaxb-api/2.3.0/jaxb-api-2.3.0.jar
8 /var/lib/buildkite-agent/.m2/repository/mysql/mysql-connector-java/5.1.46/mysql-connector-java-5.1.46.jar
8 /var/lib/buildkite-agent/.m2/repository/org/datanucleus/datanucleus-core/5.1.0-release/datanucleus-core-5.1.0-release.jar
8 /var/lib/buildkite-agent/.m2/repository/org/jooq/jooq/3.11.1/jooq-3.11.1.jar
8 /var/lib/buildkite-agent/.m2/repository/org/jooq/jooq-codegen/3.11.1/jooq-codegen-3.11.1.jar
8 /var/lib/buildkite-agent/.m2/repository/org/jooq/jooq-meta/3.11.1/jooq-meta-3.11.1.jar
```
And the list seems to be dominated by the jooq libraries. My assumption this is due to the fact that the classloaders created by the plugin are not being closed (see [`java.net.URLClassLoader#close`](http://hg.openjdk.java.net/jdk/jdk/file/tip/src/java.base/share/classes/java/net/URLClassLoader.java#l376)). This PR contains a fix for that. 

* I signed the contribution agreement
* I didn't open the issue as I was advice because I think I wanted to put all information in one place, but I'm happy to open it if needed.

### CODE REVIEW

**Comment by lukaseder** [comment]
Thank you very much for your complete PR. I agree that we should close the `URLClassLoader`, regardless if this is really the cause of the issue you've observed. Can you confirm that you're *sure* this will fix your issue, or is this just an assumption at this stage?

**Comment by lukaseder** [comment]
Will amend the change to make sure this ships only in Java 8+ distributions. The `URLClassLoader.close()` call was added in Java 7, and we still support Java 6

**Comment by lukaseder** [comment]
Integrated in jOOQ 3.12. Scheduled backport for 3.11.3 (#7631) and 3.10.9 (#7632)

**Comment by SerCeMan** [comment]
Thank you for merging

> Can you confirm that you're sure this will fix your issue, or is this just an assumption at this stage?

I believe it does fix the problem, I ran a few builds with the recompiled maven plugin, it seems like the number of loaded libraries is always one now. 

```
[serce@Sergeys-MacBook-Pro git]$ cat lsofcalls22 | awk '{print $9}' | sort | uniq -c | sort -n | grep jooq
   1 /Users/serce/.m2/repository/org/jooq/jooq-codegen-maven/3.12.0-SNAPSHOT/jooq-codegen-maven-3.12.0-SNAPSHOT.jar
   1 /Users/serce/.m2/repository/org/jooq/jooq-codegen/3.11.1/jooq-codegen-3.11.1.jar
   1 /Users/serce/.m2/repository/org/jooq/jooq-codegen/3.12.0-SNAPSHOT/jooq-codegen-3.12.0-SNAPSHOT.jar
   1 /Users/serce/.m2/repository/org/jooq/jooq-meta/3.11.1/jooq-meta-3.11.1.jar
   1 /Users/serce/.m2/repository/org/jooq/jooq-meta/3.12.0-SNAPSHOT/jooq-meta-3.12.0-SNAPSHOT.jar
   1 /Users/serce/.m2/repository/org/jooq/jooq/3.11.1/jooq-3.11.1.jar
   1 /Users/serce/.m2/repository/org/jooq/jooq/3.12.0-SNAPSHOT/jooq-3.12.0-SNAPSHOT.jar
```

**Comment by lukaseder** [comment]
OK, thanks for the confirmation.

**Pull request merged**
