### PR TITLE
Fix maven deploy

### PR DESCRIPTION
**Pull request by McNetic**
There are some errors in maven-deploy.bat. I'm not sure anyone could have got to know how to use the script without noticing and working around these...

### CODE REVIEW

**Comment by timur-sh** [comment]
Should add the same changes into `maven-deploy.sh` in the same directory?

**Comment by McNetic** [comment]
I should have looked into the shell script to compare options, sorry.

**Comment by lukaseder** [comment]
Thank you very much for your contribution. I'll look into this shortly.

In the meantime, may I ask you to review our transfer of rights agreement and sign it, so we can publish your contribution under our dual licensing model?
https://github.com/jOOQ/jOOQ/blob/master/CONTRIBUTING.md

**Comment by McNetic** [comment]
Ok, I did. Please don't add me to the contributors list as long as I did not contribute anything substantial. I do not want to answer questions regarding my contribution ;-).

**Comment by lukaseder** [comment]
> Ok, I did. Please don't add me to the contributors list as long as I did not contribute anything substantial. I do not want to answer questions regarding my contribution ;-).

OK, no worries

**Comment by lukaseder** [comment]
Thank you very much again for this contribution. Indeed, it seems as though a different version got pushed and published than the one that was tested.

**Comment by michael-simons** [comment]
I'm happy about that contribution, too.

**Pull request merged**
