### PR TITLE
Allow forced type definitions for PostgreSQL arrays

### PR DESCRIPTION
**Pull request by lightoze**
This will be a very useful addition to #4388. Not the best design, but other options I have in mind would require too big changes (e.g. extending DataTypeDefinition with a method to return full database-specific type representation).

### CODE REVIEW

**Comment by lukaseder** [comment]
Thank you very much for your suggestion. Is this fix still needed in jOOQ 3.8 (where #4388 is implemented)?

**Comment by lightoze** [comment]
Yes, having it in 3.8 is very welcome.

**Comment by lukaseder** [comment]
I meant is it still *needed* as in, does the problem persist now that #4388 is fixed in 3.8?

**Comment by lukaseder** [comment]
... perhaps your issue is not the same as #4388... I'm trying to pinpoint the problem you're having here.

**Comment by lightoze** [comment]
My issue is that I'd like to use #4388, but I'd like to configure binding for e.g. `uuid[]` type instead of specific table/column name.

**Comment by lukaseder** [comment]
There must be a misunderstanding here, I'm sorry for the confusion. From your commit, I unfortunately cannot see exactly what you're trying to fix here. Given that #4388 is fixed 8and you referred to it), I'm not sure if your fix is really needed.

So, in order to move forward with this issue, could you please:

1. Show a case where something is broken with jOOQ 3.8, i.e. some steps to reproduce the issue you're having (in code: DDL statement, Your customer converter/binding, code generation configuration, expected behaviour / actual behaviour etc.)
2. Explain why your suggested fix would solve that problem

Thank you very much.

**Comment by lightoze** [comment]
With #4388 fixed you can write:
```xml
<customType>
    <name>org.jooq.test.all.bindings.UUIDWrapperArrayBinding</name>
    <type>org.jooq.test.all.types.UUIDWrapper[]</type>
    <binding>org.jooq.test.all.bindings.UUIDWrapperArrayBinding</binding>
</customType>
```

But you cannot then use it (at least with PostgreSQL) like that:
```xml
<forcedType>
    <name>org.jooq.test.all.bindings.UUIDWrapperArrayBinding</name>
    <types>ARRAY\[UUID\]</types>
</forcedType>
```
Intention of this pull request is to make it possible to specify array type in `<types>` match. Is use case more clear now?

**Comment by lukaseder** [comment]
Oh, thank you very much for clarifying! I get it now - yes that should be possible. But it doesn't work for me in the way you suggested as the `definedType.getUserType()` value reflects what's reported by PostgreSQL's `information_schema`. In the case of a `uuid[]` type, this is, unfortunately, `_uuid`.

Also, I'd like the regex to match the usual array syntax:

```xml
<types>UUID\[\]</types>
```

I'll think of a fix for this. Thanks for the suggestion!

**Comment by lukaseder** [comment]
Hmm, I think we should re-organise 1-2 things in jOOQ-meta's internals in order to get a hold of these array types. The current implementation is not very satisfactory

**Comment by lightoze** [comment]
Yes, I agree :)
This PR is just a quick and dirty fix.

**Comment by mkurz** [comment]
@lukaseder also closed because of the `master` -> `main` rename?

**Comment by lukaseder** [comment]
Yes, the PR got closed by github due to a recent rename of the main branch. I'm going through these right now.

**Comment by lukaseder** [comment]
Anyway, I didn't agree with the implementation suggestion here. I've created an issue to keep track of this: https://github.com/jOOQ/jOOQ/issues/10285

Depending on user feedback, this issue might be prioritised in the future.

**Pull request closed without merging**
