### PR TITLE
[#5898] Field.contains(T) must not call toString() on T value

### PR DESCRIPTION
**Pull request by lmarchau**
Suggestion for issue #5898 

I found same issue with Field.startsWith(T) and Field.endsWith(T) with same cause, so I include fix here.

### CODE REVIEW

**Comment by knutwannheden** [comment]
AFAICT this issue has already been solved in 3.12. Using a test as proposed [here](https://github.com/jOOQ/jOOQ/issues/5898#issuecomment-282289532) I was not able to reproduce the problem.

@lmarchau Would it be possible for you to confirm that the problem has been solved on jOOQ master also for your particular use case?

**Comment by lmarchau** [comment]
Hi @knutwannheden ,

i'm not working on the project for more than 1 year and cannot access code now.

Sorry,

**Comment by knutwannheden** [comment]
@lmarchau Thanks for the heads-up.

**Comment by lukaseder** [comment]
The PR got closed by github due to a recent rename of the main branch.

**Pull request closed without merging**
