### PR TITLE
[#8139] preferred lazy instantiation for vals in object instances

### PR DESCRIPTION
**Pull request by astrofed**
this commit should fix [#5489] too

### CODE REVIEW

**Comment by lukaseder** [comment]
Thank you very much for your suggestion. I think this is a reasonable improvement in general, but I would definitely like to first understand the root problem and be sure how to reproduce it...

**Comment by astrofed** [comment]
I created a simple projecthttps://github.com/astrofed/jooq-codegen/commits/master

There are several commits, 2 latest are about this issue and potential fix. 

1. https://github.com/astrofed/jooq-codegen/commit/fa4add1cf218d346638895efbffde8e6b40c3f04
Here I just committed generated classes

2. https://github.com/astrofed/jooq-codegen/commit/1005329beaf87c8af44d9f655c4d62de2ab7bcc9
Here, please take a look line 37. I corrected manually this line replacing val with def and test completed successfully. Potentially I see several ways to fix it: 
    a. Replace vals with lazy vals like in my PR
    b. Replace this place in catalog generation method with def
   c. Remove this method from DefaultCatalog generally because we have a method getSchemas0  

The last decision, surely, is up to you.

The main root, the vals in the body of scala class is part of the constructor, so this val should be initialized during DefaultCatalog instantiation and it calls com.test.db.generated.Public.PUBLIC that's instantiating at the same time. This situation causes `Caused by: scala.UninitializedFieldError: Uninitialized field: .../com/test/db/generated/Public.scala: 28
	at com.test.db.generated.Public$.PUBLIC(Public.scala:28)
	at com.test.db.generated.DefaultCatalog.<init>(DefaultCatalog.scala:42)
	at com.test.db.generated.DefaultCatalog$.<init>(DefaultCatalog.scala:24)
	at com.test.db.generated.DefaultCatalog$.<clinit>(DefaultCatalog.scala)
	... 53 more
`

**Comment by lukaseder** [comment]
The PR got closed by github due to a recent rename of the main branch.

**Comment by lukaseder** [comment]
I was never able to reproduce this issue on my side. In the meantime, jOOQ 3.14 has fixed a lot of issues in the `ScalaGenerator` (https://github.com/jOOQ/jOOQ/issues/10191) - perhaps this issue here will go away

**Pull request closed without merging**
